package roidrole.tfctfud.utils;

public class Utils {

	//Estimates the probability that a random number (as generated by Random.nextGaussian) is below this number
	//Abramowitz and Stegun approximation for the normal Cumulative Density Function, error ~7.5e-8
	public static double normalCdf(double threshold) {
		double z = Math.abs(threshold);
		double t = 1.0 / (1.0 + 0.2316419 * z);
		// 1/sqrt(2π) * e^(-t²/2) — the height of this column. Needed to capture the exponential decay
		double d = 0.3989422804014327 * Math.exp(-threshold * threshold / 2.0);

		//Polynomial approximation
		double prob = d *
		t * (0.319381530 +
			t * (-0.356563782 +
				t * (1.781477937 +
					t * (-1.821255978 +
						t * 1.330274429
					)
				)
			)
		);

		if(threshold >= 0){
			return 1.0 - prob;
		} else {
			return prob;
		}
	}
}
